### ISSUE TITLE
PC版本占用CPU高

### ISSUE THREAD

**Issue by meinvtuzai** [huage2580/yuedu_hd#13]
首先说一下在PC端用着真的方便，就是源真的是有点少，如果支持更多源的话就完美了。
有一个致使的问题就是PC版本占用CPU真的是有点高，占用了24%左右，CPU的温度达到了70多，明显的温度太高了，关闭软件后CPU占用率马上降下来了，CPU温度也只有57度左右。唉！真的是硬伤呀，为啥占用CPU这么高呀，还需要优化呀，加油！

**Comment by meinvtuzai** [comment]
不会放弃了吧，汗汗，这个在PC上真的是神器呀，继续下去，加油

**Comment by huage2580** [comment]
处于不维护阶段，源使用阅读3.0的源，多找找校验下就能用。

**Comment by huage2580** [comment]
cpu占用是Flutter的bug，v230修复了
