### ISSUE TITLE
解析库闭源导致无法编译

### ISSUE THREAD

**Issue by mabDc** [huage2580/yuedu_hd#3]
即便h_parser不开源，能否提供其他途径？
比如提供一个不涉及具体解析的空方法的包。
或者允许内置1个解析吧。用于编译和调试。

**Comment by huage2580** [comment]
。。解析库会开源，有些不方便放出来，整理好会设为开放

**Comment by huage2580** [comment]
QAQ  
解析库放开权限了，理论上可以完整编译了
